// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package xdb

import (
	"context"
)

const selectPair = `-- name: SelectPair :one
SELECT
    value,
    revision
FROM persistencekit.keyspace_pair
WHERE keyspace_id = $1
AND key = $2
`

type SelectPairParams struct {
	ID  int64
	Key []byte
}

type SelectPairRow struct {
	Value    []byte
	Revision int64
}

func (q *Queries) SelectPair(ctx context.Context, arg SelectPairParams) (SelectPairRow, error) {
	row := q.db.QueryRowContext(ctx, selectPair, arg.ID, arg.Key)
	var i SelectPairRow
	err := row.Scan(&i.Value, &i.Revision)
	return i, err
}

const upsertKeyspace = `-- name: UpsertKeyspace :one
INSERT INTO persistencekit.keyspace (
    name
) VALUES (
    $1
) ON CONFLICT (name) DO UPDATE SET
    name = EXCLUDED.name
RETURNING id
`

func (q *Queries) UpsertKeyspace(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertKeyspace, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}
