version: "3.8"

services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    ports:
      - "29000:9000/tcp"
      - "29001:9001/tcp"

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "28000:8000/tcp"
